SELECT 
 A.GROUP_PRODUCT,B.NAMA_GROUP,B.HPP,B.PERSEDIAAN,B.PENJUALAN,A.PRODUK_ID,A.PRODUK_DESC,
A.AWAL,A.AWAL_RP,
A.MUTASI_IN,A.BELI,A.BELI_RP,A.RET_BELI,A.RET_BELI_RP,A.EKSPEDISI,A.EKSPEDISI_RP,A.MUTASI_OUT,
A.JUAL,A.JUAL_RP,A.JUAL_REAL,
A.JUAL_BY_EVAP,
A.JUAL_BY_EVAP_RP,
A.RET_JUAL,A.RET_JUAL_RP,
A.MUTASI_IN_RP,A.MUTASI_OUT_RP,
A.CONSIN , A.CONSIN_RP,A.CONSIN_BY_EVAP,A.CONSIN_BY_EVAP_RP,
A.CONSOUT,A.CONSOUT_RP,
A.AKHIR,a.produk_id+' '+a.group_product+' '+b.nama_group+' '+b.hpp+' '+b.persediaan+' '+b.penjualan+' '+a.produk_desc as is_find
 FROM (
SELECT IM_PRODUK.GROUP_PRODUCT,IM_PRODUK.PRODUK_ID,
			IM_PRODUK.PRODUK_DESC,
	ISNULL(AWAL.AWAL,0) AS AWAL,
    ISNULL(AWAL.AWAL_RP,0) AS AWAL_RP,
ISNULL(CONSIN.QTY,0)  CONSIN,
ISNULL(CONSIN.NILAI,0) CONSIN_RP,
ISNULL(CONSIN_BY_EVAP.QTY,0) CONSIN_BY_EVAP,
ISNULL(CONSIN_BY_EVAP.NILAI,0) CONSIN_BY_EVAP_RP,
ISNULL(CONSOUT.CONSOUT,0) CONSOUT,
ISNULL(CONSOUT.CONSOUT_RP,0) CONSOUT_RP,
ISNULL(JUAL.QTY,0) AS JUAL,  
            ISNULL(JUAL.JUAL_RP,0) + ISNULL(JUAL_BY_EVAP.JUAL_RP2,0) AS JUAL_RP, 
            ISNULL(JUAL.NILAI,0) AS JUAL_REAL, 
ISNULL(JUAL_BY_EVAP.QTY,0) AS JUAL_BY_EVAP,
ISNULL(JUAL_BY_EVAP.NILAI,0) AS JUAL_BY_EVAP_RP,
 			ABS(ISNULL(RET_JUAL.RET_JUAL,0)) AS RET_JUAL,   
            ABS(ISNULL(RET_JUAL.RET_JUAL_RP,0)) AS RET_JUAL_RP,
			ABS(ISNULL(STOK.BELI,0)) AS BELI,
            ISNULL(STOK_RP.BELI,0) + ISNULL(STOK_RP.EKSPEDISI,0) AS BELI_RP,
--ISNULL(STOK_RP.BELI,0)AS BELI_RP,
            ABS(ISNULL(STOK_RP.RET_BELI,0.00)) AS RET_BELI_RP,
			ABS(ISNULL(STOK.RET_BELI,0)) AS RET_BELI,
			ABS(ISNULL(STOK.MUTASI_IN,0)) AS MUTASI_IN,
            ABS(ISNULL(STOK_RP.MUTASI_IN,0)) AS MUTASI_IN_RP,
			ABS(ISNULL(STOK.MUTASI_OUT,0))  AS MUTASI_OUT,
            ABS(ISNULL(STOK_RP.MUTASI_OUT,0)) AS MUTASI_OUT_RP,
            ISNULL(STOK_RP.EKSPEDISI,0)AS EKSPEDISI_RP,
            ISNULL(STOK.EKSPEDISI,0) AS EKSPEDISI,
			(ABS(ISNULL(AWAL.AWAL,0)) - ABS(ISNULL(JUAL.QTY,0)) - ABS(ISNULL(JUAL_BY_EVAP.QTY,0)) + ABS(ISNULL(RET_JUAL.RET_JUAL,0))  
			+ ABS(ISNULL(STOK.BELI,0)) - ABS(ISNULL(STOK.RET_BELI,0)) - ABS(ISNULL(CONSOUT.CONSOUT,0)) + ABS(ISNULL(CONSIN.QTY,0)) +
            ABS(ISNULL(CONSIN_BY_EVAP.QTY,0)) + ABS(ISNULL(STOK.MUTASI_IN,0)) -  ABS(ISNULL(STOK.MUTASI_OUT,0)) ) AS AKHIR
  	FROM IM_PRODUK,
			(  SELECT 	(SINV.STOK_ID) AS KEY1,   
							SUM(SINV.QTY) AS AWAL,
					         SUM(SINV.NILAI) AS AWAL_RP,
							AVG(SINV.HPP_AVG) AS HPP_AVG
				FROM     SINV 
			WHERE    	( MONTH(SINV.PERIODE) = MONTH(:arg_tgl)) AND
							( YEAR(SINV.PERIODE) = YEAR(:arg_tgl)) 
			   GROUP BY (SINV.STOK_ID)   
			) AWAL,
	
			(  SELECT 	SINV.STOK_ID AS STOK_ID,   
							SUM(SINV.NILAI) AS AWAL
				FROM     SINV  
			WHERE    	( MONTH(SINV.PERIODE) = MONTH(:arg_tgl)) AND
							( YEAR(SINV.PERIODE) = YEAR(:arg_tgl)) 
			   GROUP BY SINV.STOK_ID   
			) AWAL_RP,

			( SELECT A.STOK_ID,SUM(A.QTY) AS QTY,SUM(A.NILAI) as NILAI,SUM(A.JUAL_RP) JUAL_RP
            FROM
                (
                SELECT B.STOK_ID,B.QTY,B.STOK_ID+ISNULL(B.EVAP,'') AS KEY1,B.QTY * ISNULL(B.HPP,0) as NILAI,
                B.NETTO * ISNULL(A.KURS,1) as JUAL_RP
                FROM TSALES1 A,TSALES2 B
                WHERE A.BUKTI_ID = B.BUKTI_ID
                AND A.TIPE_TRANS = '22'
                AND ISNULL(B.EVAP,'') = ''
                AND A.TGL BETWEEN :arg_tgl AND:arg_tgl2
                AND ISNULL(B.qty,0) <> 0
                AND A.ORDER_OKE = 'Y'
                AND B.STOK_ID+ISNULL(B.EVAP,'') NOT IN
                    (
                        SELECT B.STOK_ID+ISNULL(B.EVAP,'') 
                        FROM TSALES1 A,TSALES2 B
                        WHERE A.BUKTI_ID = B.BUKTI_ID
                        AND A.TIPE_TRANS = '88'
                        AND A.TGL < :arg_tgl)
                )A
                 GROUP BY A.STOK_ID
			) JUAL,
(
        SELECT A.STOK_ID,SUM(A.QTY) AS QTY,SUM(A.QTY * ISNULL(A.HPP,0)) AS NILAI,SUM(A.JUAL_RP2) JUAL_RP2
FROM
    (
    SELECT B.STOK_ID,B.QTY,ISNULL(B.HPP,0) AS HPP,B.STOK_ID+ISNULL(B.EVAP,'') AS KEY1,
	ISNULL(B.NETTO,0) * ISNULL(A.KURS,1) AS JUAL_RP2
    FROM TSALES1 A,TSALES2 B
    WHERE A.BUKTI_ID = B.BUKTI_ID
    AND A.TIPE_TRANS = '22'
    AND ISNULL(B.EVAP,'') <> ''
    AND ISNULL(B.QTY,0) <> 0
    AND A.TGL BETWEEN :arg_tgl AND:arg_tgl2
    )A
    GROUP BY A.STOK_ID
 )JUAL_BY_EVAP,   

( SELECT 	(TSALES2.STOK_ID) AS KEY1,   
	SUM(CASE WHEN TSALES1.TIPE_TRANS = '88' THEN TSALES2.QTY ELSE 0 END ) AS CONSOUT,
		SUM(CASE WHEN TSALES1.TIPE_TRANS = '88' THEN ( TSALES2.HPP * TSALES2.QTY)  ELSE 0 END )  AS CONSOUT_RP					
				FROM   	TSALES1,   
							TSALES2
			  WHERE 	( TSALES1.BUKTI_ID = TSALES2.BUKTI_ID ) AND  
							(TSALES1.TGL BETWEEN :arg_tgl AND:arg_tgl2) AND
							( TSALES1.ORDER_OKE = 'Y' ) AND
							ISNULL(TSALES2.QTY,0) <>0
			   GROUP BY (TSALES2.STOK_ID)
			) CONSOUT,


			( SELECT 	(TSALES2.STOK_ID) AS KEY1,							
							SUM(CASE WHEN TSALES1.TIPE_TRANS IN ('32','26','36') THEN TSALES2.QTY ELSE 0 END ) AS RET_JUAL,	
							SUM(CASE WHEN TSALES1.TIPE_TRANS IN ('32','26','36') THEN ABS(( TSALES2.NETTO)    * ISNULL(TSALES1.KURS,1)) ELSE 0 END )  AS RET_JUAL_RP						
							
				FROM   	TSALES1,   
							TSALES2  ,MCUST
			  WHERE 	( TSALES1.BUKTI_ID = TSALES2.BUKTI_ID ) AND  
							TSALES1.CUST_ID = MCUST.CUST_ID AND
							(TSALES1.TGL BETWEEN :arg_tgl AND:arg_tgl2) AND
							ISNULL(TSALES2.QTY,0) <>0 AND
							ISNULL(TSALES2.HRG,0) <> 0 AND
							TSALES1.tipe_trans in('32','26','36')
			   GROUP BY (TSALES2.STOK_ID)
			) RET_JUAL,

	

			( SELECT 	(TSTOK2.STOK_ID) AS KEY1,   
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '02' THEN TSTOK2.QTY ELSE 0 END ) AS BELI,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '12' THEN TSTOK2.QTY ELSE 0 END ) AS RET_BELI,
	                        SUM( CASE WHEN TSTOK1.TIPE_TRANS = '88' THEN TSTOK2.QTY ELSE 0 END ) AS CONSIN,
	                        SUM( CASE WHEN TSTOK1.TIPE_TRANS = '05'  THEN TSTOK2.QTY ELSE 0 END ) AS EKSPEDISI,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '09'  THEN TSTOK2.QTY ELSE 0 END ) AS MUTASI_IN,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '19'  THEN TSTOK2.QTY ELSE 0 END ) AS MUTASI_OUT
				FROM  	TSTOK1,   
							TSTOK2,IM_PRODUK,IM_PRODUCT_GROUP
				 WHERE 	( TSTOK1.BUKTI_ID = TSTOK2.BUKTI_ID ) AND  
IM_PRODUK.PRODUK_ID = TSTOK2.STOK_ID AND
IM_PRODUK.GROUP_PRODUCT = IM_PRODUCT_GROUP.KODE_GROUP AND
							(TSTOK1.TGL BETWEEN :arg_tgl AND:arg_tgl2) AND
                              ( TSTOK1.ORDER_OKE = 'Y' ) AND
							ISNULL(TSTOK2.QTY,0) <> 0
			   GROUP BY (TSTOK2.STOK_ID)
			 ) STOK,

			( SELECT 	TSTOK2.STOK_ID AS STOK_ID,   
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '02' THEN ( TSTOK2.NETTO * ISNULL(TSTOK1.KURS,1) )   ELSE 0 END) AS BELI,
SUM( CASE WHEN TSTOK1.TIPE_TRANS = '88' THEN (TSTOK2.NETTO * ISNULL(TSTOK1.KURS,1))    ELSE 0 END) AS CONSIN,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '12' THEN ABS(TSTOK2.NETTO_HPP) ELSE 0 END ) AS RET_BELI,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '09' THEN (TSTOK2.NETTO) ELSE 0 END ) AS MUTASI_IN,
							SUM( CASE WHEN TSTOK1.TIPE_TRANS = '19' THEN ABS(TSTOK2.NETTO_HPP) ELSE 0 END ) AS MUTASI_OUT,
                            SUM( CASE WHEN TSTOK1.TIPE_TRANS = '05' THEN ABS(TSTOK2.BIAYA_EKSPEDISI)*ABS(ISNULL(TSTOK2.QTY,0)) ELSE 0 END ) AS EKSPEDISI

				FROM  	TSTOK1,   
							TSTOK2,IM_PRODUK,IM_PRODUCT_GROUP
				 WHERE 	( TSTOK1.BUKTI_ID = TSTOK2.BUKTI_ID ) AND  
IM_PRODUK.PRODUK_ID = TSTOK2.STOK_ID AND
IM_PRODUK.GROUP_PRODUCT = IM_PRODUCT_GROUP.KODE_GROUP AND
							(TSTOK1.TGL BETWEEN :arg_tgl AND:arg_tgl2) AND
							( ISNULL(TSTOK1.ORDER_OKE,'N') = 'Y' ) AND
							ISNULL(TSTOK2.QTY,0) <> 0
			   GROUP BY TSTOK2.STOK_ID
			 ) STOK_RP,
(
        SELECT A.STOK_ID,SUM(A.QTY) AS QTY,SUM(A.QTY * ISNULL(A.NETTO,0)) AS NILAI
    FROM
        (
        SELECT B.STOK_ID,B.QTY,B.STOK_ID+ISNULL(B.COA_ID,'') AS KEY1,B.NETTO
        FROM TSTOK1 A,TSTOK2 B
        WHERE A.BUKTI_ID = B.BUKTI_ID
        AND A.TIPE_TRANS = '88'
        AND ISNULL(B.QTY,0) <> 0
        AND A.TGL BETWEEN :arg_tgl AND:arg_tgl2
        AND B.STOK_ID + ISNULL(B.COA_ID,'') NOT IN
            (
            SELECT B.STOK_ID+ISNULL(B.EVAP,'')
            FROM TSALES1 A,TSALES2 B
            WHERE A.BUKTI_ID = B.BUKTI_ID
            AND A.TIPE_TRANS = '88'
            AND A.TGL < :arg_tgl)
            )A
        GROUP BY A.STOK_ID
)CONSIN,
(
SELECT A.STOK_ID,SUM(A.QTY) AS QTY,SUM(A.QTY * ISNULL(B.HPP,0)) AS NILAI
    FROM
        (
        SELECT B.STOK_ID,B.QTY,B.STOK_ID+ISNULL(B.COA_ID,'') AS KEY1
        FROM TSTOK1 A,TSTOK2 B
        WHERE A.BUKTI_ID = B.BUKTI_ID
        AND A.TIPE_TRANS = '88'
        AND ISNULL(B.QTY,0) <> 0
        AND A.TGL BETWEEN :arg_tgl AND:arg_tgl2
        )A,
        (
        SELECT B.STOK_ID+ISNULL(B.EVAP,'') AS KEY1,ISNULL(B.HPP,0) AS HPP
        FROM TSALES1 A,TSALES2 B
        WHERE A.BUKTI_ID = B.BUKTI_ID
        AND A.TIPE_TRANS = '88'
        AND ISNULL(B.QTY,0) <> 0
        AND A.TGL < :arg_tgl
        )B
        WHERE A.KEY1 = B.KEY1
        GROUP BY A.STOK_ID
        )CONSIN_BY_EVAP

WHERE	IM_PRODUK.STOK_ITEM = 'Y' AND
			(IM_PRODUK.PRODUK_ID *= AWAL.KEY1) AND
			(IM_PRODUK.PRODUK_ID *= JUAL.STOK_ID) AND
            (IM_PRODUK.PRODUK_ID *= JUAL_BY_EVAP.STOK_ID) AND
			(IM_PRODUK.PRODUK_ID *= CONSOUT.KEY1) AND
			(IM_PRODUK.PRODUK_ID *= RET_JUAL.KEY1) AND
			(IM_PRODUK.PRODUK_ID *= STOK.KEY1) AND
			(IM_PRODUK.PRODUK_ID *= AWAL_RP.STOK_ID) AND
         	(IM_PRODUK.PRODUK_ID *= STOK_RP.STOK_ID) AND
            (IM_PRODUK.PRODUK_ID *= CONSIN_BY_EVAP.STOK_ID) AND
            (IM_PRODUK.PRODUK_ID *= CONSIN.STOK_ID)             
ORDER BY IM_PRODUK.PRODUK_ID ASC
) A,IM_PRODUCT_GROUP B 
WHERE A.GROUP_PRODUCT = B.KODE_GROUP AND
((a.group_product = :arg_group) or 1 = :arg_all1) and
((a.awal <>0 or a.awal_rp <>0 or a.mutasi_in <> 0 or a.beli <> 0 or a.beli_rp <>0 or
a.ret_beli<>0 or a.ret_beli_rp <> 0 or a.ekspedisi <> 0 or a.ekspedisi_rp <> 0 or a.mutasi_out <> 0 or a.jual <> 0 or a.ret_jual <> 0 or jual_by_evap <> 0 or consin_by_evap <> 0) or 1 = :arg_zero) 
AND ((A.akhir <0) or 1 = :flag_minus)
