-- ============================================================
-- DIAGNOSA: Root cause query vs ledger
-- ============================================================
CREATE VARIABLE arg_tgl1 DATE;
SET arg_tgl1 = '2026-01-01';

-- [1] TIPE_TRANS di AP_TRANS
OUTPUT TO 'C:\\BTV\\debug\\diag1_aptrans_tipe.txt' FORMAT ASCII DELIMITED BY ',' QUOTE '';
SELECT TIPE_TRANS, COUNT(*) AS JML FROM AP_TRANS GROUP BY TIPE_TRANS ORDER BY TIPE_TRANS;

-- [2] Apakah vendor 200.xxx ada di AP_TRANS?
OUTPUT TO 'C:\\BTV\\debug\\diag2_vendor200.txt' FORMAT ASCII DELIMITED BY ',' QUOTE '';
SELECT TOP 5 VENDOR_ID, ORDER_CLIENT, TIPE_TRANS, TGL FROM AP_TRANS WHERE VENDOR_ID LIKE '200.%' ORDER BY TGL DESC;

-- [3] SALDO_AWAL_FAKTUR tipe_trans 1 vs 2
OUTPUT TO 'C:\\BTV\\debug\\diag3_saldo_tipe.txt' FORMAT ASCII DELIMITED BY ',' QUOTE '';
SELECT TIPE_TRANS, COUNT(*) AS JML_FAKTUR, SUM(NEW_SALDO) AS TOTAL_IDR
FROM SALDO_AWAL_FAKTUR
WHERE MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026
GROUP BY TIPE_TRANS;

-- [4] Apakah SALDO_AWAL_FAKTUR TIPE_TRANS=1 ada di AP_TRANS?
OUTPUT TO 'C:\\BTV\\debug\\diag4_cross.txt' FORMAT ASCII DELIMITED BY ',' QUOTE '';
SELECT TOP 10 S.BUKTI_ID, S.VENDOR_ID, S.TIPE_TRANS, S.NEW_SALDO,
    (SELECT COUNT(*) FROM AP_TRANS A WHERE A.ORDER_CLIENT = S.BUKTI_ID AND A.TIPE_TRANS IN ('02','05','06','12','16')) AS ADA_DI_AP_TRANS
FROM SALDO_AWAL_FAKTUR S
WHERE S.TIPE_TRANS = 1 AND MONTH(S.PERIODE) = 1 AND YEAR(S.PERIODE) = 2026
ORDER BY S.BUKTI_ID;

-- [5] Selisih total: semua tipe_trans vs hanya tipe=2
OUTPUT TO 'C:\\BTV\\debug\\diag5_selisih.txt' FORMAT ASCII DELIMITED BY ',' QUOTE '';
SELECT 
    'Semua' AS KET, SUM(NEW_SALDO) AS TOTAL_IDR, COUNT(DISTINCT BUKTI_ID) AS JML
FROM SALDO_AWAL_FAKTUR
WHERE MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026
UNION ALL
SELECT 
    'Hanya TIPE=2', SUM(NEW_SALDO), COUNT(DISTINCT BUKTI_ID)
FROM SALDO_AWAL_FAKTUR
WHERE TIPE_TRANS = 2 AND MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026;

OUTPUT TO STDOUT;
SELECT 'DIAGNOSA SELESAI' AS STATUS;
