OUTPUT TO 'C:\BTV\debug\diag88_piutang_jan_validate_out.txt' FORMAT ASCII DELIMITED BY '|' QUOTE '';
SELECT
    COUNT(*) AS ROWS,
    CAST(SUM(SALDO_AWAL_IDR) AS DECIMAL(18,2)) AS SA,
    CAST(SUM(MUTASI_IDR) AS DECIMAL(18,2)) AS MU,
    CAST(SUM(ADJ_IDR) AS DECIMAL(18,2)) AS ADJ,
    CAST(SUM(NILAI_BAYAR_IDR) AS DECIMAL(18,2)) AS BYR,
    CAST(SUM(SISA_IDR) AS DECIMAL(18,2)) AS SISA
FROM (
SELECT
    MAIN.CUST_ID,
    MAIN.SALDO_AWAL_IDR,
    MAIN.MUTASI_IDR,
    MAIN.ADJ_IDR,
    MAIN.NILAI_BAYAR_IDR,
    (MAIN.SALDO_AWAL_IDR + MAIN.MUTASI_IDR + MAIN.ADJ_IDR - MAIN.NILAI_BAYAR_IDR) AS SISA_IDR
FROM (
