SELECT TOP 50
    SAF.BUKTI_ID,
    SAF.VENDOR_ID,
    SAF.CURR_ID,
    CAST(SUM(CASE WHEN ISNULL(SAF.NEW_SALDO,0) <> 0 THEN SAF.NEW_SALDO
                  WHEN ISNULL(SAF.SALDO,0) <> 0 THEN SAF.SALDO
                  WHEN ISNULL(SAF.NEW_RATE,0) <> 0 THEN ISNULL(SAF.SALDO_KURS,0) * SAF.NEW_RATE
                  ELSE ISNULL(SAF.SALDO_KURS,0) * ISNULL(SAF.RATE,1)
             END) AS DECIMAL(18,2)) AS OPENING_IDR,
    CAST(SUM(CASE WHEN ISNULL(SAF.NEW_SALDO_KURS,0) <> 0 THEN SAF.NEW_SALDO_KURS ELSE ISNULL(SAF.SALDO_KURS,0) END) AS DECIMAL(18,4)) AS OPENING_KURS,
    COUNT(*) AS ROWS
FROM SALDO_AWAL_FAKTUR SAF
WHERE SAF.TIPE_TRANS = 1
  AND SAF.PERIODE >= '2026-01-01'
  AND SAF.PERIODE < '2026-02-01'
  AND NOT EXISTS (
      SELECT 1
      FROM gl_journal GJ
      WHERE GJ.account_id = '103-001'
        AND GJ.debet > 0
        AND GJ.voucher = SAF.BUKTI_ID
  )
GROUP BY SAF.BUKTI_ID, SAF.VENDOR_ID, SAF.CURR_ID
ORDER BY ABS(OPENING_IDR) DESC, SAF.BUKTI_ID;
