-- ============================================================
-- DIAGNOSA: Kenapa hasil query tidak sama dengan ledger
-- ============================================================

-- [1] Cek tipe_trans apa saja yang ada di AP_TRANS
-- Apakah 200.xxx vendor masuk AP_TRANS atau tabel lain?
SELECT TIPE_TRANS, COUNT(*) AS JML, MIN(TGL) AS TGL_AWAL, MAX(TGL) AS TGL_AKHIR
FROM AP_TRANS
GROUP BY TIPE_TRANS
ORDER BY TIPE_TRANS;

-- [2] Cek apakah vendor 200.xxx ada di AP_TRANS
SELECT TOP 5 VENDOR_ID, ORDER_CLIENT, TIPE_TRANS, TGL, TTL_NETTO
FROM AP_TRANS
WHERE VENDOR_ID LIKE '200.%'
ORDER BY TGL DESC;

-- [3] Cek SALDO_AWAL_FAKTUR: berapa banyak TIPE_TRANS 1 vs 2 untuk Januari 2026
SELECT TIPE_TRANS, COUNT(*) AS JML_FAKTUR, SUM(NEW_SALDO) AS TOTAL_IDR
FROM SALDO_AWAL_FAKTUR
WHERE MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026
GROUP BY TIPE_TRANS;

-- [4] Cek contoh BUKTI_ID dari SALDO_AWAL_FAKTUR TIPE_TRANS=1 apakah ada di AP_TRANS
SELECT TOP 5 S.BUKTI_ID, S.VENDOR_ID, S.TIPE_TRANS, S.NEW_SALDO,
    (SELECT COUNT(*) FROM AP_TRANS A WHERE A.ORDER_CLIENT = S.BUKTI_ID) AS ADA_DI_AP_TRANS
FROM SALDO_AWAL_FAKTUR S
WHERE S.TIPE_TRANS = 1 AND MONTH(S.PERIODE) = 1 AND YEAR(S.PERIODE) = 2026;

-- [5] Cek apakah 200.xxx vendor ORDER_CLIENT ada di tabel lain (bukan AP_TRANS)
-- Cari tabel yang punya kolom ORDER_CLIENT dan VENDOR_ID
SELECT 'AP_TRANS' AS TABEL, COUNT(*) AS JML FROM AP_TRANS WHERE VENDOR_ID LIKE '200.%'
UNION ALL
SELECT 'AP_TRANS_TOTAL', COUNT(*) FROM AP_TRANS WHERE VENDOR_ID NOT LIKE '4SL.%' AND VENDOR_ID NOT LIKE 'X%';

-- [6] Hitung total SISA yang HARUSNYA ada (dari SALDO_AWAL_FAKTUR semua tipe_trans)
-- vs yang tertangkap query (hanya TIPE_TRANS=2)
SELECT 
    'Semua TIPE_TRANS' AS KET, 
    SUM(NEW_SALDO) AS TOTAL_SALDO_IDR, 
    COUNT(DISTINCT BUKTI_ID) AS JML_FAKTUR
FROM SALDO_AWAL_FAKTUR
WHERE MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026
UNION ALL
SELECT 
    'Hanya TIPE_TRANS=2 (yang tertangkap query)', 
    SUM(NEW_SALDO),
    COUNT(DISTINCT BUKTI_ID)
FROM SALDO_AWAL_FAKTUR
WHERE TIPE_TRANS = 2 AND MONTH(PERIODE) = 1 AND YEAR(PERIODE) = 2026;
