OUTPUT TO 'C:\BTV\debug\diag73_total.txt' FORMAT ASCII DELIMITED BY '|' QUOTE '';
SELECT
    CAST((SELECT SUM(CASE WHEN ISNULL(NEW_SALDO,0) <> 0 THEN NEW_SALDO
                          WHEN ISNULL(SALDO,0) <> 0 THEN SALDO
                          WHEN ISNULL(NEW_RATE,0) <> 0 THEN ISNULL(SALDO_KURS,0) * NEW_RATE
                          ELSE ISNULL(SALDO_KURS,0) * ISNULL(RATE,1)
                     END)
          FROM SALDO_AWAL_FAKTUR
          WHERE TIPE_TRANS = 1
            AND PERIODE >= '2026-01-01'
            AND PERIODE < '2026-02-01') AS DECIMAL(18,2)) AS ALL_SAF,
    CAST((SELECT SUM(CASE WHEN ISNULL(SAF.NEW_SALDO,0) <> 0 THEN SAF.NEW_SALDO
                          WHEN ISNULL(SAF.SALDO,0) <> 0 THEN SAF.SALDO
                          WHEN ISNULL(SAF.NEW_RATE,0) <> 0 THEN ISNULL(SAF.SALDO_KURS,0) * SAF.NEW_RATE
                          ELSE ISNULL(SAF.SALDO_KURS,0) * ISNULL(SAF.RATE,1)
                     END)
          FROM SALDO_AWAL_FAKTUR SAF
          WHERE SAF.TIPE_TRANS = 1
            AND SAF.PERIODE >= '2026-01-01'
            AND SAF.PERIODE < '2026-02-01'
            AND SAF.BUKTI_ID IN (
                SELECT DISTINCT GJ.voucher
                FROM gl_journal GJ
                WHERE GJ.account_id = '103-001'
                  AND GJ.debet > 0
            )) AS DECIMAL(18,2)) AS GL_ANCHORED,
    CAST(
        (SELECT SUM(CASE WHEN ISNULL(NEW_SALDO,0) <> 0 THEN NEW_SALDO
                         WHEN ISNULL(SALDO,0) <> 0 THEN SALDO
                         WHEN ISNULL(NEW_RATE,0) <> 0 THEN ISNULL(SALDO_KURS,0) * NEW_RATE
                         ELSE ISNULL(SALDO_KURS,0) * ISNULL(RATE,1)
                    END)
         FROM SALDO_AWAL_FAKTUR
         WHERE TIPE_TRANS = 1
           AND PERIODE >= '2026-01-01'
           AND PERIODE < '2026-02-01')
        -
        (SELECT SUM(CASE WHEN ISNULL(SAF.NEW_SALDO,0) <> 0 THEN SAF.NEW_SALDO
                         WHEN ISNULL(SAF.SALDO,0) <> 0 THEN SAF.SALDO
                         WHEN ISNULL(SAF.NEW_RATE,0) <> 0 THEN ISNULL(SAF.SALDO_KURS,0) * SAF.NEW_RATE
                         ELSE ISNULL(SAF.SALDO_KURS,0) * ISNULL(SAF.RATE,1)
                    END)
         FROM SALDO_AWAL_FAKTUR SAF
         WHERE SAF.TIPE_TRANS = 1
           AND SAF.PERIODE >= '2026-01-01'
           AND SAF.PERIODE < '2026-02-01'
           AND SAF.BUKTI_ID IN (
               SELECT DISTINCT GJ.voucher
               FROM gl_journal GJ
               WHERE GJ.account_id = '103-001'
                 AND GJ.debet > 0
           ))
    AS DECIMAL(18,2)) AS DIFF_IDR;

OUTPUT TO 'C:\BTV\debug\diag73_missing_anchor.txt' FORMAT ASCII DELIMITED BY '|' QUOTE '';
SELECT TOP 100
    SAF.BUKTI_ID,
    SAF.VENDOR_ID,
    SAF.CURR_ID,
    CAST(SUM(CASE WHEN ISNULL(SAF.NEW_SALDO,0) <> 0 THEN SAF.NEW_SALDO
                  WHEN ISNULL(SAF.SALDO,0) <> 0 THEN SAF.SALDO
                  WHEN ISNULL(SAF.NEW_RATE,0) <> 0 THEN ISNULL(SAF.SALDO_KURS,0) * SAF.NEW_RATE
                  ELSE ISNULL(SAF.SALDO_KURS,0) * ISNULL(SAF.RATE,1)
             END) AS DECIMAL(18,2)) AS OPENING_IDR,
    CAST(SUM(CASE WHEN ISNULL(SAF.NEW_SALDO_KURS,0) <> 0 THEN SAF.NEW_SALDO_KURS ELSE ISNULL(SAF.SALDO_KURS,0) END) AS DECIMAL(18,4)) AS OPENING_KURS,
    COUNT(*) AS ROWS
FROM SALDO_AWAL_FAKTUR SAF
WHERE SAF.TIPE_TRANS = 1
  AND SAF.PERIODE >= '2026-01-01'
  AND SAF.PERIODE < '2026-02-01'
  AND NOT EXISTS (
      SELECT 1
      FROM gl_journal GJ
      WHERE GJ.account_id = '103-001'
        AND GJ.debet > 0
        AND GJ.voucher = SAF.BUKTI_ID
  )
GROUP BY SAF.BUKTI_ID, SAF.VENDOR_ID, SAF.CURR_ID
ORDER BY ABS(OPENING_IDR) DESC, SAF.BUKTI_ID;

OUTPUT TO 'C:\BTV\debug\diag73_rounding.txt' FORMAT ASCII DELIMITED BY '|' QUOTE '';
SELECT
    CAST(SUM(ISNULL(NEW_SALDO, 0)) AS DECIMAL(18,2)) AS SUM_NEW_SALDO,
    CAST(SUM(ISNULL(SALDO, 0)) AS DECIMAL(18,2)) AS SUM_SALDO,
    CAST(SUM(ISNULL(SALDO_KURS, 0) * ISNULL(NEW_RATE, 0)) AS DECIMAL(18,2)) AS SUM_KURS_X_NEW_RATE,
    CAST(SUM(ROUND(ISNULL(SALDO_KURS, 0) * ISNULL(NEW_RATE, 0), 2)) AS DECIMAL(18,2)) AS SUM_ROUND_ROW_KURS_X_NEW_RATE,
    CAST(SUM(ROUND(ISNULL(NEW_SALDO, 0), 2)) AS DECIMAL(18,2)) AS SUM_ROUND_ROW_NEW_SALDO
FROM SALDO_AWAL_FAKTUR
WHERE TIPE_TRANS = 1
  AND PERIODE >= '2026-01-01'
  AND PERIODE < '2026-02-01';

OUTPUT TO 'C:\BTV\debug\diag73_per_bukti_delta.txt' FORMAT ASCII DELIMITED BY '|' QUOTE '';
SELECT TOP 100
    SAF.BUKTI_ID,
    SAF.VENDOR_ID,
    SAF.CURR_ID,
    CAST(SUM(ISNULL(SAF.NEW_SALDO, 0)) AS DECIMAL(18,2)) AS SUM_NEW_SALDO,
    CAST(SUM(ISNULL(SAF.SALDO_KURS, 0) * ISNULL(SAF.NEW_RATE, 0)) AS DECIMAL(18,2)) AS SUM_KURS_NEW_RATE,
    CAST(SUM(ROUND(ISNULL(SAF.SALDO_KURS, 0) * ISNULL(SAF.NEW_RATE, 0), 2)) AS DECIMAL(18,2)) AS SUM_ROW_ROUND_KURS_NEW_RATE,
    CAST(SUM(ROUND(ISNULL(SAF.NEW_SALDO, 0), 2)) AS DECIMAL(18,2)) AS SUM_ROW_ROUND_NEW_SALDO,
    CAST(SUM(ISNULL(SAF.NEW_SALDO, 0)) - SUM(ISNULL(SAF.SALDO_KURS, 0) * ISNULL(SAF.NEW_RATE, 0)) AS DECIMAL(18,2)) AS DELTA_NEW_SALDO_VS_RATE
FROM SALDO_AWAL_FAKTUR SAF
WHERE SAF.TIPE_TRANS = 1
  AND SAF.PERIODE >= '2026-01-01'
  AND SAF.PERIODE < '2026-02-01'
GROUP BY SAF.BUKTI_ID, SAF.VENDOR_ID, SAF.CURR_ID
HAVING ABS(SUM(ISNULL(SAF.NEW_SALDO, 0)) - SUM(ISNULL(SAF.SALDO_KURS, 0) * ISNULL(SAF.NEW_RATE, 0))) <> 0
ORDER BY ABS(DELTA_NEW_SALDO_VS_RATE) DESC, SAF.BUKTI_ID;

OUTPUT TO STDOUT;
SELECT 'DIAG73_DONE' AS STATUS;
