$ErrorActionPreference = 'Stop'
$conn = New-Object System.Data.Odbc.OdbcConnection("DSN=vsp;Uid=dba;Pwd=jakarta;")
$conn.Open()
function T($label, $q) {
    $c = $conn.CreateCommand(); $c.CommandText = $q; $c.CommandTimeout = 600
    $t0 = Get-Date
    $n = 0
    try {
        $r = $c.ExecuteReader(); while ($r.Read()) { $n++ }; $r.Close()
        "{0,-40} rows={1,-5} sec={2:F2}" -f $label, $n, ((New-TimeSpan $t0 (Get-Date)).TotalSeconds)
    } catch { "$label ERR: $($_.Exception.Message)" }
}
$t1='2026-03-01'; $t2='2026-03-31'; $ys="DATEADD(day,1-DATEPART(dayofyear,'$t1'),'$t1')"; $tend="DATEADD(day,1,'$t2')"

$inv = @"
SELECT JANGKAR.ORDER_CLIENT, MAX(A.TGL) TGL, MAX(A.VENDOR_ID) VENDOR_ID, MAX(A.CURR_ID) CURR_ID, MAX(A.TIPE_TRANS) TIPE_TRANS, MAX(A.KURS) KURS
FROM (
  SELECT AT.ORDER_CLIENT FROM AP_TRANS AT WHERE AT.TIPE_TRANS IN ('02','05','06','12','16') AND AT.TGL >= '$t1' AND AT.TGL < $tend
    AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=AT.ORDER_CLIENT AND GJ.account_id='226-001' AND GJ.kredit>0)
  UNION SELECT SAF2.BUKTI_ID FROM SALDO_AWAL_FAKTUR SAF2 WHERE SAF2.TIPE_TRANS IN (1,2) AND SAF2.PERIODE >= $ys AND SAF2.PERIODE < DATEADD(month,1,$ys)
    AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=SAF2.BUKTI_ID AND GJ.account_id='226-001' AND GJ.kredit>0)
  UNION SELECT AT2.ORDER_CLIENT FROM AP_TRANS AT2 WHERE AT2.TIPE_TRANS IN ('02','05','06','12','16') AND AT2.TGL >= $ys AND AT2.TGL < '$t1'
    AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=AT2.ORDER_CLIENT AND GJ.account_id='226-001' AND GJ.kredit>0)
) JANGKAR
LEFT JOIN AP_TRANS A ON A.ORDER_CLIENT = JANGKAR.ORDER_CLIENT AND A.TIPE_TRANS IN ('02','05','06','12','16')
GROUP BY JANGKAR.ORDER_CLIENT
"@

T 'INV-only' "SELECT COUNT(*) FROM ($inv) X"
T 'INV+OPN' "SELECT COUNT(*) FROM ($inv) INV LEFT JOIN (SELECT BUKTI_ID, SUM(SALDO) S FROM SALDO_AWAL_FAKTUR WHERE TIPE_TRANS IN (1,2) AND PERIODE >= $ys AND PERIODE < DATEADD(month,1,$ys) AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=BUKTI_ID AND GJ.account_id='226-001' AND GJ.kredit>0) GROUP BY BUKTI_ID) O ON O.BUKTI_ID=INV.ORDER_CLIENT"
T 'INV+MUT' "SELECT COUNT(*) FROM ($inv) INV LEFT JOIN (SELECT ORDER_CLIENT, SUM(TTL_NETTO) S FROM AP_TRANS WHERE TGL >= $ys AND TGL < $tend AND ORDER_OKE='Y' AND TIPE_TRANS IN ('02','05','12','06','16') AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=AP_TRANS.ORDER_CLIENT AND GJ.account_id='226-001' AND GJ.kredit>0) GROUP BY ORDER_CLIENT) M ON M.ORDER_CLIENT=INV.ORDER_CLIENT"
T 'INV+BYR' "SELECT COUNT(*) FROM ($inv) INV LEFT JOIN (SELECT T2.BUKTI_ID, SUM(T2.NILAI_BAYAR) S FROM TBYR1 T1 INNER JOIN TBYR2 T2 ON T2.VOUCHER=T1.VOUCHER WHERE T1.FLAG_BAYAR IN (1,2) AND T1.TGL >= $ys AND T1.TGL < $tend AND EXISTS (SELECT 1 FROM gl_journal GJ WHERE GJ.voucher=T2.BUKTI_ID AND GJ.account_id='226-001' AND GJ.kredit>0) GROUP BY T2.BUKTI_ID) B ON B.BUKTI_ID=INV.ORDER_CLIENT"
T 'INV+SUPP+CUST' "SELECT COUNT(*) FROM ($inv) INV LEFT JOIN MCSTSUPP S ON S.VENDOR_ID=INV.VENDOR_ID LEFT JOIN MCUST C ON C.cust_id=INV.VENDOR_ID"

$conn.Close()
