-- Fix nama aset (recovered dari WP_Aset tetap_TAM 2026.xlsx via tgl+harga)
-- 91 aset. Jalankan di DB produksi juga.
UPDATE FA_ASSET SET asset_name='Motor Honda Vario 150 ESP' WHERE site_id='101' AND asset_code='KDR-0008' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Grand Max (PT.Tam)' WHERE site_id='101' AND asset_code='KDR-0009' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Kijang Inova' WHERE site_id='101' AND asset_code='KDR-0010' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Kijang Inova-Assecories Innova' WHERE site_id='101' AND asset_code='KDR-0011' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Proton Exora Thn2009' WHERE site_id='101' AND asset_code='KDR-0012' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Toyota Innova G 2009' WHERE site_id='101' AND asset_code='KDR-0013' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Motor Honda Vario Black' WHERE site_id='101' AND asset_code='KDR-0014' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Motor N-MAX' WHERE site_id='101' AND asset_code='KDR-0015' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Toyota Camry A/T 2015' WHERE site_id='101' AND asset_code='KDR-0016' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Mitsubishi Expander Ultimate' WHERE site_id='101' AND asset_code='KDR-0017' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Mobil Mitsubishi Expander Ultimate' WHERE site_id='101' AND asset_code='KDR-0018' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Mobil Mitsubishi Expander Ultimate' WHERE site_id='101' AND asset_code='KDR-0019' AND asset_name='3';
UPDATE FA_ASSET SET asset_name='Motor Yamaha PCX 150CBS' WHERE site_id='101' AND asset_code='KDR-0020' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Toyota Innova Zenix 2.0 Q HV CVT' WHERE site_id='101' AND asset_code='KDR-0021' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Toyota All New Veloz 1.5 Q CVT' WHERE site_id='101' AND asset_code='KDR-0022' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil Daihatsu Grand Max MB 1.5 D PS' WHERE site_id='101' AND asset_code='KDR-0023' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Motor Honda Vario 160ABS' WHERE site_id='101' AND asset_code='KDR-0024' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mobil JAECOO-J7-SHS' WHERE site_id='101' AND asset_code='KDR-0025' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit LAPTOP - VIVO BOOK + Antivirus' WHERE site_id='101' AND asset_code='PKT-0128' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Printer' WHERE site_id='101' AND asset_code='PKT-0129' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit UPS GPOWER GP200 800VA' WHERE site_id='101' AND asset_code='PKT-0130' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Dispenser' WHERE site_id='101' AND asset_code='PKT-0131' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Desktop ASUS' WHERE site_id='101' AND asset_code='PKT-0132' AND asset_name='4';
UPDATE FA_ASSET SET asset_name='Unit Printer EPSON L3110' WHERE site_id='101' AND asset_code='PKT-0133' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Printer EPSON L3150' WHERE site_id='101' AND asset_code='PKT-0134' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit PC AIO LENOVO' WHERE site_id='101' AND asset_code='PKT-0135' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit LAPTOP- LENOVO 141TL05' WHERE site_id='101' AND asset_code='PKT-0136' AND asset_name='3';
UPDATE FA_ASSET SET asset_name='Unit LAPTOP- LENOVO Ideapad Slim' WHERE site_id='101' AND asset_code='PKT-0137' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit TP-Link 16 Port Gigabit Smart Switch' WHERE site_id='101' AND asset_code='PKT-0138' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Komputer Lenovo A10' WHERE site_id='101' AND asset_code='PKT-0139' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Printer Epson L-3210' WHERE site_id='101' AND asset_code='PKT-0140' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='License PB Appeon 50%' WHERE site_id='101' AND asset_code='PKT-0141' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='License PB Appeon sisa 50% Lunas' WHERE site_id='101' AND asset_code='PKT-0142' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Komputer Lenovo A.10A340' WHERE site_id='101' AND asset_code='PKT-0143' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='RAM Server DIMM 16GB PC2400 SK HYNIX' WHERE site_id='101' AND asset_code='PKT-0144' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit AC Merk GREE' WHERE site_id='101' AND asset_code='PKT-0145' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Tangga Multiporse 4x4 Step' WHERE site_id='101' AND asset_code='PKT-0146' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 2 PK' WHERE site_id='101' AND asset_code='PKT-0147' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Printer Epson L-3210' WHERE site_id='101' AND asset_code='PKT-0148' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 1 PK' WHERE site_id='101' AND asset_code='PKT-0149' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='SSD Server + Stabilizer' WHERE site_id='101' AND asset_code='PKT-0151' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 1 PK' WHERE site_id='101' AND asset_code='PKT-0152' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Dispenser merk SHARP' WHERE site_id='101' AND asset_code='PKT-0153' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 2 PK' WHERE site_id='101' AND asset_code='PKT-0154' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Set Office Chair Lionet 1' WHERE site_id='101' AND asset_code='PKT-0155' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Printer Epson LQ-310' WHERE site_id='101' AND asset_code='PKT-0156' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 2 PK' WHERE site_id='101' AND asset_code='PKT-0157' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit LCD Monitor' WHERE site_id='101' AND asset_code='PKT-0158' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Laptop LENOVO R7773' WHERE site_id='101' AND asset_code='PKT-0159' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Laptop LENOVO R5753' WHERE site_id='101' AND asset_code='PKT-0160' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Set CCTV - Bali' WHERE site_id='101' AND asset_code='PKT-0161' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Computer Core I7 - 7000' WHERE site_id='101' AND asset_code='PKT-0162' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Set Vertical Blind - Bangunan Bali' WHERE site_id='101' AND asset_code='PKT-0163' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit TV HISENE 43' WHERE site_id='101' AND asset_code='PKT-0164' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit LAPTOP NB MODERN' WHERE site_id='101' AND asset_code='PKT-0165' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit PRINTER HP SMART TANK 580' WHERE site_id='101' AND asset_code='PKT-0166' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Set Roller Blind - Ruang Meeting' WHERE site_id='101' AND asset_code='PKT-0167' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Proyektor Infocus' WHERE site_id='101' AND asset_code='PKT-0168' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Printer HP Smart 520' WHERE site_id='101' AND asset_code='PKT-0169' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Buah Kursi IC046' WHERE site_id='101' AND asset_code='PKT-0170' AND asset_name='5';
UPDATE FA_ASSET SET asset_name='Unit Mesin Absensi' WHERE site_id='101' AND asset_code='PKT-0171' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Dispenser SHARP SWD7' WHERE site_id='101' AND asset_code='PKT-0172' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Laptop LENOVO Yoga' WHERE site_id='101' AND asset_code='PKT-0173' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit PRINTER HP Smart Tank 580 Wifi' WHERE site_id='101' AND asset_code='PKT-0174' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit PRINTER HP Smart Tank 580 Wifi' WHERE site_id='101' AND asset_code='PKT-0175' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit KOMPUTER Desktop Core i7' WHERE site_id='101' AND asset_code='PKT-0176' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit AC Merk GREE 2 PK' WHERE site_id='101' AND asset_code='PKT-0177' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Monitor 22"' WHERE site_id='101' AND asset_code='PKT-0178' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Mesin Las' WHERE site_id='101' AND asset_code='PBK-0014' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Digital Multimeter' WHERE site_id='101' AND asset_code='PBK-0015' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Clamp Meter' WHERE site_id='101' AND asset_code='PBK-0016' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Refrigeran Leak Detector' WHERE site_id='101' AND asset_code='PBK-0017' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Temperatur Data Logger' WHERE site_id='101' AND asset_code='PBK-0018' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Digital Manifold Testo' WHERE site_id='101' AND asset_code='PBK-0019' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Digital Manifold Testo 570' WHERE site_id='101' AND asset_code='PBK-0020' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Infrared Thermometer' WHERE site_id='101' AND asset_code='PBK-0021' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='High Presurre' WHERE site_id='101' AND asset_code='PBK-0022' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Pompa Shimizu' WHERE site_id='101' AND asset_code='PBK-0023' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mesin Bor Makita' WHERE site_id='101' AND asset_code='PBK-0024' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Clamp Thermo Operated' WHERE site_id='101' AND asset_code='PBK-0025' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='V-Belt Tension Meter RTM' WHERE site_id='101' AND asset_code='PBK-0026' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Temperatus Data, USB Conection' WHERE site_id='101' AND asset_code='PBK-0027' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Dongkrak Botol 32 Ton + Bracket' WHERE site_id='101' AND asset_code='PBK-0028' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Mesin Bor Batere DF333' WHERE site_id='101' AND asset_code='PBK-0029' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Unit Pompa Air Shimizu PC 268' WHERE site_id='101' AND asset_code='PBK-0030' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Pcs TESTO -Temperature Data' WHERE site_id='101' AND asset_code='PBK-0033' AND asset_name='8';
UPDATE FA_ASSET SET asset_name='Unit BOR Dudukkan 16 MM' WHERE site_id='101' AND asset_code='PBK-0034' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Pompa Air Shimizu' WHERE site_id='101' AND asset_code='PBK-0035' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Pompa Air Shimizu ( Mess )' WHERE site_id='101' AND asset_code='PBK-0036' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Set Cutting Gloor / Mata Blender' WHERE site_id='101' AND asset_code='PBK-0037' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Hand Pallet 3 Ton' WHERE site_id='101' AND asset_code='PBK-0038' AND asset_name='1';

-- 3 aset acquisition_date NULL (dicocokkan via cost):
UPDATE FA_ASSET SET asset_name='Unit AC Merk PANASONIC 2 PK' WHERE site_id='101' AND asset_code='PKT-0150' AND asset_name='1';
UPDATE FA_ASSET SET asset_name='Unit Pompa Air Shimizu PC 1353 + PC 268' WHERE site_id='101' AND asset_code='PBK-0031' AND asset_name='2';
UPDATE FA_ASSET SET asset_name='Pcs Timbangan ECO - Freon' WHERE site_id='101' AND asset_code='PBK-0032' AND asset_name='2';
